// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Entry struct {
	ID        int64 `json:"id"`
	WalletID  int64 `json:"wallet_id"`
	PaymentID int64 `json:"payment_id"`
	// +credit / -debit
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Payment struct {
	ID         int64 `json:"id"`
	FromUserID int64 `json:"from_user_id"`
	ToUserID   int64 `json:"to_user_id"`
	// must be > 0
	Amount int64 `json:"amount"`
	// pending | completed | failed
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Email          string    `json:"email"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}

type Wallet struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	// must be >= 0
	Balance   int64     `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
}
