// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment.sql

package db

import (
	"context"
)

const cancelPayment = `-- name: CancelPayment :one
UPDATE payments
SET status = 'canceled'
WHERE id = $1
    AND status = 'pending'
    RETURNING id, from_user_id, to_user_id, amount, status, created_at
`

func (q *Queries) CancelPayment(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, cancelPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    from_user_id,
    to_user_id,
    amount,
    status
) VALUES (
             $1, $2, $3, 'pending'
         )
    RETURNING id, from_user_id, to_user_id, amount, status, created_at
`

type CreatePaymentParams struct {
	FromUserID int64 `json:"from_user_id"`
	ToUserID   int64 `json:"to_user_id"`
	Amount     int64 `json:"amount"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment, arg.FromUserID, arg.ToUserID, arg.Amount)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, from_user_id, to_user_id, amount, status, created_at FROM payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Amount,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, from_user_id, to_user_id, amount, status, created_at FROM payments
WHERE from_user_id = $1 OR
      to_user_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListPaymentsParams struct {
	FromUserID int64 `json:"from_user_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments, arg.FromUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
