// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddWalletBalance(ctx context.Context, arg AddWalletBalanceParams) (Wallet, error)
	CancelPayment(ctx context.Context, id int64) (Payment, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	DeleteWallet(ctx context.Context, id int64) error
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetPayment(ctx context.Context, id int64) (Payment, error)
	GetWallet(ctx context.Context, id int64) (Wallet, error)
	GetWalletForUpdate(ctx context.Context, id int64) (Wallet, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error)
	ListWallets(ctx context.Context, arg ListWalletsParams) ([]Wallet, error)
	UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error)
}

var _ Querier = (*Queries)(nil)
