name: Deploy to production

on:
  push:
    branches: [ main ]


jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure Render credentials
        run: curl -f -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}